dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp local_settings.travis.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: decidejossouvil
  strategy: git
  api_key:
    secure: T/JT/Ngq47TRCf/MpnPjFGirlWICjyZqc5Xcl7qrVka8y3EbgfctiahY8EFngRngORixe0spTXT0uxubhwjslUuPCCIm7sbPq+9RJUPaUpCv0iLilwaeYU7rZXckaZ2OK++8K58LsEjN+5oOHEPabj/VouwF8vrFEpc0lcrLWUh5/+u7nSqK1Kz7qrP5b1mYyiEccgz37l5CNYzgB25j/Q/JcjFbsJh/Vvpru5hVHktHU/8VRQXS5SoqM70yra4PwJ00xmJucgMHLgRUFYqsG8DKQnVjrBpZmHy7M9vgjuUAG6Gl1pIUbzyXDgtnOs8/HBmZCXSSPD7Un6yh1MiPn0qTpeN4DXscZaMjMX+xr7mwHKn5giAFz/9gnIJtC//GQto2iy3yc2rjBN9vbf7PBj1+WghDZtcGchXbmN2Srn3BCGYlT3vK3vXpePT8RCQAo1ag8sGLwFLZKvwY+gaLYk0Scg+k5Fm/0HDjSQomA6trFUAbWvf56I/58oxb/Gioz2YhmksXoqw1gJdQZAA/bQe98fbFrRXMHvXQ4gZNuIiG1cnUpeoPDU/r8reUhIoAIG1RuBvb6YZlp0Tvem/AbfUkaFgOa9FXiEo1bM8UM1qTBVG1GA/XYlIT9BV+6QYIo5nfNsWgrswrQ9bJL7eKqEMBwD5rFMNcC8iTN4pQLSk=
